### ISSUE TITLE
Peer feedback W2

### ISSUE THREAD

**Issue by lars-ruijs** [joordy/web-app-from-scratch-2021#13]
### ✅ Done
- [X] Short description in the about section 
- [X] Link to live preview in the about section and README
- [X] Repository is open for issues
- [X] Repo includes a .gitignore
- [X] Includes an installation guide
- [X] Includes used sources
- [X] Includes Actor and Interaction diagrams
- [X] Includes information about the data (API) that is used. 

### 📌 To-do
- [x] Add a more detailed description of what you are creating in the README

## Actor Diagram
- Still a bit confusing. The heading names don't always match the module structure. For example: in the diagram it looks like the Event.js module contains 3 functions, while it actually contains two and refers to a third (fetchQuery.js) which is located in a different module. 
- In the "API" section of the actor diagram, it mentions the function setVariable() twice. 

### 📌 To-do
- [x] Scan your module structure again and see how the modules are linked.

### ✅ Done
- [X] The flow makes sense with how your application works.
-  Note: the heading names don't always match the module structure. 

### ✅ Done
- [X] The preview looks great! ✨ 
- [X] The search function works like expected.
- [X] It renders a detail page on click.
- [X] You are already integrating a photo editor which is working!!

### 📌 Improvements
- [x] If I click an image it goes to the detail page, but only shows the image when I refresh the page. 
- [x] It would be really cool if the download button would download the picture with the effects (nice to have).

### ✅ Done
- [X] The code has been structured into modules (see my feedback about the interaction diagram above)
- [X] Logical names for functions and variables. 
- [X] Your code seems efficient. 

### 📌 Improvements
- [x] Consider looking into using more const in stead of let variables. 

You are doing very well in my opinion and already have a super nice application up and running! The extras will make it even more realistic.

**Comment by joordy** [comment]
## Repository & README

- [ ] Add a more detailed description of what you are creating in the README

## Actor Diagram

- [ ] Scan your module structure again and see how the modules are linked.

## Improvements

- [ ] If I click an image it goes to the detail page, but only shows the image when I refresh the page.
- [ ] It would be really cool if the download button would download the picture with the effects (nice to have).


## Code:
- [ ] Consider looking into using more const in stead of let variables.
