### ISSUE TITLE
Peer feedback

### ISSUE THREAD

**Issue by lars-ruijs** [joordy/web-app-from-scratch-2021#2]
### ✅ Done
- [X] Short description in the about section 
- [X] Link to live preview in the about section and README
- [X] Repository is open for issues
- [X] Repo includes a .gitignore
- [X] Include an installation guide
- [X] Include used sources

### 📌 To-do
- [x] Maybe add the .eslint and .prettier configuration files to your .gitignore
- [x] Add a more detailed description of what your creating in the README
- [x] Include info about which API you are using and what data you use from it

## Code 
- Codeflow looks clear
- You could consider adding more code comments 
- You are already using modules to split code
- The names of functions and variables make sense

The first version of your preview already looks very nice!
